name: Update JSON Release
on:
  push:
    paths:
      - 'anime.json'
jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: anime.json
          tag_name: "latest" 
          prerelease: false
          draft: false
